### ISSUE TITLE
How to set the `websites_enabled_category_codes` parameter?

### ISSUE THREAD

**Issue by nunesgh** [ooni/probe-cli#130]
Hi,

I have installed probe-cli but I could not find anywhere how to properly set the `websites_enabled_category_codes` parameter on `.ooniprobe/config.json`.

By default, it is set as `null`, but I would like to set specific categories as described [here](https://ooni.org/get-involved/contribute-test-lists/#what-are-test-lists).

Thank you in advance.

**Comment by tomac4t** [comment]
@nunesgh I believe `websites_enabled_category_codes` is supported, here is my config:

```json
{
  "_": "This is your OONI Probe config file. See https://ooni.io/help/probe-cli for help",
  "_version": 1,
  "_informed_consent": true,
  "sharing": {
    "include_ip": false,
    "include_asn": true,
    "include_country": true,
    "upload_results": true
  },
  "nettests": {
    "websites_url_limit": 0,
    "websites_enabled_category_codes": [
      "NEWS",
      "GOVT"
    ]
  },
  "advanced": {
    "send_crash_reports": true,
    "collector_url": "",
    "bouncer_url": "https://bouncer.ooni.io"
  }
}
```

**Comment by nunesgh** [comment]
Thank you for your reply, @tomac4t!

Do you know whether the `collector_url` parameter should be filled somehow?

**Comment by tomac4t** [comment]
@nunesgh Leave this blank is ok. I think it will try the `collector_url` from https://bouncer.ooni.io/api/v1/collectors. Of course, you can fill the `collector_url` with `https://ams-ps2.ooni.nu` or `https://mia-ps2.ooni.nu` etc. But I believe the onion hidden service is not supported by probe-cli yet.

**Comment by nunesgh** [comment]
Thank you so much, @tomac4t!
