### ISSUE TITLE
custom scan

### ISSUE THREAD

**Issue by kalashnikov2** [ooni/probe-cli#136]
Hello

I have a CSV file in OONI format
XXX.csv
What is the command to run a custom scan?

help doesn't show much

`./ooniprobe --help
usage: ooniprobe [<flags>] <command> [<args> ...]

Flags:
      --help           Show context-sensitive help (also try --help-long and --help-man).
  -c, --config=CONFIG  Set a custom config file path
  -v, --verbose        Enable verbose log output.
      --batch          Enable batch command line usage.
      --software-name="ooniprobe-cli"  
                       Override application name
      --software-version="3.0.0"  
                       Override the application version
      --version        Show application version.

Commands:
  help [<command>...]
    Show help.

  geoip
    Perform a geoip lookup

  info
    Display information about OONI Probe

  list [<id>]
    List results

  onboard [<flags>]
    Starts the onboarding process

  reset [<flags>]
    Cleanup an old or experimental installation

  rm [<flags>] [<id>]
    Delete a result

  run websites

  run im

  run performance

  run middlebox

  run circumvention

  run all*

  show <id>
    Show a specific measurement

  upload
    Upload a specific measurement

  version
    Show version.
`

**Comment by tian2992** [comment]
Also wondering, on how to run a single domain.

**Comment by bassosimone** [comment]
The next release will allow you to run `ooniprobe run websites --input <URL> [--input <URL> ...] --input-file <FILE> [--input-file <FILE> ...]`. The file format will be such that you need to specify a single URL per line. Given a CSV, therefore, one needs to extra only the column that contains the URLs. Assuming that the first field contains the URL, this can be obtained by using `cat $csv_file | awk -F, '{print $1}'`. Thank you for your patience!

**Comment by bassosimone** [comment]
(Oh, also: the next release of probe-cli will happen in our next development sprint: i.e. in the next 15 days.)
