### ISSUE TITLE
session config update in nettest groups missing

### ISSUE THREAD

**Issue by cyBerta** [ooni/probe-cli#173]
While working on #171 I was running into the following issue: 
When adding the riseupvpn experiment to the nettest group 'circumvention' the riseupvpn experiment succeeds if it's started before the psiphon experiment but not in the opposite order. 

The error log shows:

```
   • Running test nettests.RiseupVPN
   • status.queued   
   • status.started  
   • status.measurement_start
   • Getting CA certificate; please be patient...
[engine] > GET https://black.riseup.net/ca.crt
[engine] > Accept-Language: en-US;q=0.8,en;q=0.5
[engine] > User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
[engine] > Host: black.riseup.net
[engine] > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[engine] >
[engine] dial 127.0.0.1:36201/tcp...
[engine] dial 127.0.0.1:36201/tcp... <nil> in 137.757µs
[engine] < socks connect tcp 127.0.0.1:36201->black.riseup.net:443: unknown error general SOCKS server failure
   ⨯ Getting CA certificate failed. Aborting test.
   • Fetching: 0 &{127 riseupvpn 2020-11-17 23:03:06.552885108 +0000 UTC 0.019547017 true false false { false} false { false} false { false} {0 false} {0 false} {false false}  54 { false} {/home/cyberta/.ooniprobe/msmts/circumvention-2020-11-17T230300.809434495Z/msmt-riseupvpn-0.json true}}
```

Psiphon is doing a GET request before the Riseup test is running using the same local IP+port.

```
• OnProgress: 0.083333 - psiphon experiment running
   2.78% psiphon experiment running 
[engine] > GET https://www.google.com/humans.txt
[engine] > Host: www.google.com
[engine] > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[engine] > Accept-Language: en-US;q=0.8,en;q=0.5
[engine] > User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
[engine] >
[engine] dial 127.0.0.1:36201/tcp...
[engine] dial 127.0.0.1:36201/tcp... <nil> in 130.033µs
[engine] tls {sni=www.google.com next=[h2 http/1.1]}...
[engine] tls {sni=www.google.com next=[h2 http/1.1]}... <nil> in 28.718808ms {next=h2 cipher=TLS_AES_128_GCM_SHA256 v=TLSv1.3}
[engine] < 200
```

So RiseupVPN is trying to connect via the psiphon tunnel which is not correct. So far I didn't find a way to force the cli to not use the established tunnel.

**Comment by bassosimone** [comment]
@cyBerta very good catch! I've started addressing the problem at https://github.com/ooni/probe-engine/pull/1051, but, as explained in there, I think there's a bunch of things I need to think about. This part of the codebase is not very tidy and it seems to me by spotting this bug you also served me an opportunity for clarification and simplification.

It may take a few days for me to finish this work, because I am also working on other tasks. In the meanwhile, if you could perhaps test whether https://github.com/ooni/probe-engine/commit/d2b0b7abab4a0a613ce27c297e27bcd25385577a fixes the original issue you reported, I would be grateful. (I think it should but I only tested miniooni so far.)

Thank you!

**Comment by cyBerta** [comment]
Great, I'll test that commit later tonight.

**Comment by cyBerta** [comment]
ooni/probe-engine@d2b0b7a fixes the reported issue :partying_face:

**Comment by bassosimone** [comment]
When https://github.com/ooni/probe-cli/pull/184 is merged, probe-cli will contains the fix in https://github.com/ooni/probe-engine/pull/1051. Merging is pending once the automatic checks complete. Apologies for the delay it took me to fully fix the issue.
