### ISSUE TITLE
Fails to load correct CA certificate bundle

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-cli#20]
Tests fail to run because measurement-kit seems to be given `/etc/ssl/cert.pem` as the `CA_BUNDLE_PATH` value which doesn't exist by default on Linux. It works fine when `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` is exported to the environment when running `./ooni run test_name`

![image](https://user-images.githubusercontent.com/700829/46847697-acfe7f00-cdb3-11e8-86e5-d7c2810b8bff.png)

**Comment by hellais** [comment]
I believe there is some way to build measurement-kit with embedded certs, but we are not using that currently.

@bassosimone is this correct?

**Comment by bassosimone** [comment]
@hellais we should be using it on all platforms. I am not 100% sure we will be able to forward port this feature when we will use cURL in the future, but I hope I am wrong.

**Comment by bassosimone** [comment]
FTR, in https://github.com/measurement-kit/go-measurement-kit/pull/10 I've added reasonable default paths for macOS and most Linux distributions. This should help, even though the best solution is probably the one of downloading a CA bundle and using it. (The Go engine won't need this, but the C engine needs it.) Consider using https://github.com/measurement-kit/generic-assets

**Comment by hellais** [comment]
This should be fixed in 3.0.0-beta.2
