### ISSUE TITLE
Report files are not saved after submission

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-cli#21]
On Linux, this happens when the temporary directory where the files are created and the `$OONI_HOME` directory are on different file systems. In the below case `/home` resides on a separate disk partition.

![image](https://user-images.githubusercontent.com/700829/46847956-05824c00-cdb5-11e8-8739-cf1a259e7d70.png)

**Comment by hellais** [comment]
Ah damn, I see the problem.

I guess the correct solution to this problem should be that instead of using the global tmp file location we create a tmp directory inside of the `OONI_HOME` so that `os.rename` can be called.

**Comment by sarathms** [comment]
That brings up the question of cleaning up the temporary files from the `$OONI_HOME`. Why not just copy the files from `/tmp`? Is there a significantly big performance gain from the using `os.Rename`?
