### ISSUE TITLE
How to build probe-cli on *linux ?

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-cli#22]
It seems that the [instructions](https://github.com/ooni/probe-cli#linux) are incomplete on how to build probe-cli on *linux systems.
Specifically the part after building measurement kit: 
> You should now have a set of compiled libraries inside of MK_DIST. Take this and copy it into `vendor/github.com/measurement-kit/go-measurement-kit/libs/linux.`

What is the correct PATH or where exactly should I copy the measurement kit compiled libraries?

**Comment by hellais** [comment]
You can download a pre-built ooni binary in the releases tab: https://github.com/ooni/probe-cli/releases/download/v3.0.0-beta.1/ooniprobe_3.0.0-beta.1_linux_amd64.tar.gz.

It's also, actually, no longer necessary to build build the measurement-kit dependency manually, so I have update the Readme.md to reflect this.
