### ISSUE TITLE
dep ensure Lockfile absolute path error

### ISSUE THREAD

**Issue by physkets** [ooni/probe-cli#23]
When I run `dep ensure`, I see the following message:

`unable to create lock pkg/dep/sm.lock: Lockfiles must be given as absolute path names`

Is that a bug?

**Comment by physkets** [comment]
I've never used `dep` or even `Go` before this, so I don't know. I am also using the same version of `dep`.

**Comment by hellais** [comment]
Ah ok I see. Did you setup the necessary golang environment variables and set it up according to: https://golang.org/doc/code.html#Organization.

Some things to check are:
* You have set the `GOPATH` and `GOROOT` environment variables to appropriate locations in `~/.bashrc or `~/.zshrc`
* You have added `GOROOT/bin` & `GOPATH/bin` to your `PATH` env var
* You have cloned the ooni/probe-cli repo inside of `$GOPATH/src/github.com/ooni/probe-cli`

**Comment by hellais** [comment]
We have now switched to using go mod, so I believe this should no longer be an issue. If it still is please file a new issue.
