### ISSUE TITLE
Mention not implemented config options

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-cli#25]
The config file should mention options that have no effect or not currently used similar to the help page message: `this function is not implemented`.

**Comment by hellais** [comment]
Currently it's probably easier to document what is implemented (in terms of settings), than what is not implemented.

These are the settings that should work:
* `sharing` -> all of them
* `advanced.send_crash_reports`
* `advanced.bouncer_url`
* `advanced.collector_url` (will work as a failover when bouncer communication does not work)

**Comment by bassosimone** [comment]
@hellais do we want to implement all config options for the release? Are there any feature that we may want to not ship to let the release happen sooner?

**Comment by hellais** [comment]
I think the most high priority config options are documented in: https://github.com/ooni/probe-cli/issues/39
