### ISSUE TITLE
Upgrade to measurement-kit 0.9.1 and drop legacy maxmind db support

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-cli#27]
According to "[GeoLite Legacy databases are now discontinued](https://support.maxmind.com/geolite-legacy-discontinuation-notice/)", the URLs we use to download the GeoIP databases no longer work. The link also talks about possible migration paths.

Edit: Thanks to @chinmayisk for pointing out the problem.

**Comment by hellais** [comment]
We noticed recently this issue when installing this from scratch on linux. It seems like maxmind isn't hosting the legacy databases anymore and therefore you need to manually download them from ooni-resources: https://github.com/OpenObservatory/ooni-resources/releases/download/26/maxmind-geoip.GeoIP.dat.gz & https://github.com/OpenObservatory/ooni-resources/releases/download/26/maxmind-geoip.GeoIPASNum.dat.gz

uncompress them and place them inside of your OONI_HOME (default `~/.ooni`).

We should definitely prioritise doing the upgrade as currently the install is broken.
