### ISSUE TITLE
Integrate the linux build.sh into goreleaser and maybe add Makefile targets

### ISSUE THREAD

**Issue by hellais** [ooni/probe-cli#31]
As mentioned in https://github.com/ooni/probe-cli/pull/29#pullrequestreview-236208149 we should evaluate merging the build.sh into the `Makefile`

**Comment by bassosimone** [comment]
@hellais it seems to me we want to build releases with Go releaser. Isn't Go releaser already handling the parallelism for itself? (Do we need Makefile and build.sh if we use Go releaser?)

**Comment by hellais** [comment]
Yes you are right goreleaser does handle parallelism. I guess the only argument in favour of using a `Makefile` is that it's a common entry point to build tooling and it supports autocompletion out of the box in many shell configurations.

Maybe the plan should be that of figuring out how to integrate stuff from build.sh into goreleaser (currently it's just the linux build which doesn't work in goreleaser).

**Comment by bassosimone** [comment]
> Maybe the plan should be that of figuring out how to integrate stuff from build.sh into goreleaser (currently it's just the linux build which doesn't work in goreleaser).

Yeah, that seems like a good direction where to Go :-P

**Comment by bassosimone** [comment]
Not now. As said in #62, maybe later. Will reopen or create new issue.
