### ISSUE TITLE
Rename the CLI from `ooni` to `ooniprobe`

### ISSUE THREAD

**Issue by hellais** [ooni/probe-cli#34]
Currently the CLI for probe is called `ooni`, which is different from how it was before and doesn't include the name `probe` in it.

I am thinking that we should consider renaming it to either `ooniprobe` or `ooprobe` or something else that includes the name `probe` in it.

We may not want to make it be the same as the older ooniprobe to avoid conflict or we may want to do that so that people notice the change.

**Comment by hellais** [comment]
We came to the conclusion with @bassosimone that we should probably be preserving the original name `ooniprobe` even if the CLI is not fully compatible with the old CLI.

We should probably do the rename prior to the stable release to minimise confusion.

**Comment by bassosimone** [comment]
Totally
