### ISSUE TITLE
Build script changes break download script on probe-desktop

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-cli#64]
The released assets now have an additional segment in the file names viz. `$(git describe)`
![image](https://user-images.githubusercontent.com/700829/66150158-96fc5680-e5e2-11e9-8b89-66408a351db3.png)

These files are now not downloadable using the release version tag in the [download script](https://github.com/ooni/probe-desktop/blob/master/scripts/download-bin.js#L8) on `probe-desktop`

The file ` ooniprobe_checksums.txt` is also missing from the downloadable assets. which was being used by the download script.

Are these changes intended and to be reflected in `probe-desktop` too?

**Comment by bassosimone** [comment]
> Are these changes intended and to be reflected in probe-desktop too?

Not necessarily. I was not aware of a procedure for downloading files that was so precisely codified, so I just published binaries that looked okay to me. Are you able to use them anyway,?

**Comment by bassosimone** [comment]
Update: have read the code. Is it correct to say that the linked code is meant to be executed offline and not by the ooniprobe-desktop instance, or am I missing something @sarathms?

**Comment by hellais** [comment]
@bassosimone if you could generate the filenames in a compatible format (and with the checksums) it's likely going to be easier to integrate into the existing dev tooling of probe-desktop.

> linked code is meant to be executed offline and not by the ooniprobe-desktop instance

Yes that is correct. I suppose that if you make changes to the probe-desktop download bin script it could also work, though you may also want to grep inside of the source tree of probe-desktop to understand if some assumptions on the filename structure exists elsewhere.

**Comment by bassosimone** [comment]
Yeah, I guess it is easier to change it at the source.
