### ISSUE TITLE
Make it possible to cleanly stop a currently running test session

### ISSUE THREAD

**Issue by hellais** [ooni/probe-cli#76]
Currently if you hit ctrl-c while a test is running, it will not shutdown cleanly and you will end up with a bunch of test results in the `is_done: false` state which will mean they are not shown in the result listing.

This is about adding support for handling the `SIGINT` signal and doing a clean shutdown so as to close the current report which is open and put the measurements in a consistent state.

**Comment by bassosimone** [comment]
Yeah, we need to modify the way in which `probe-cli` work to have a cancellable context that is cancelled when the user hits `^C`. There is a bunch of cases where the cancellation cannot probably be immediate, unless we further refactor code inside of probe-engine to cope with that. In principle, most Go code is cancellable, if you use a `context.Context`. We do that in `probe-engine` but it may be that some operations are not immediately cancellable anyway (e.g. blocked for I/O), thus there is need to wrap them in a goroutine to make them fully cancellable.

**Comment by hellais** [comment]
This has been implemented in #84.
